import {escapeHtml,normalizeRequest,normalizeDraft,approvePublic,sha256,token,publicCode} from './core.mjs';
import {makeWord} from './word.mjs';
import {layout,entry,bespoke,login,staff,proposal} from './views.mjs';
const SESSION_AGE=60*60*12;
const MAX_JSON=28000;
const respond=(obj,status=200,headers={})=>new Response(JSON.stringify(obj),{status,headers:{'content-type':'application/json;charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff',...headers}});
const html=(body,status=200,indexable=false)=>new Response(body,{status,headers:{'content-type':'text/html;charset=utf-8','cache-control':indexable?'public,max-age=300':'private,no-store','x-robots-tag':indexable?'index,follow':'noindex,nofollow','x-content-type-options':'nosniff'}});
const err=(msg,status=400)=>respond({ok:false,error:msg},status);
const wrap=async (request,fn)=>{try{return await fn()}catch(e){const msg=String(e?.message||'Unexpected error');if(e?.isUserError)return err(msg,400);console.error('JoTrip request failed',msg);return err('Yêu cầu chưa thực hiện được. Vui lòng thử lại.',500)}};
function security(r, bespoke=false){const h=new Headers(r.headers);h.set('x-frame-options','DENY');h.set('referrer-policy','strict-origin-when-cross-origin');h.set('x-content-type-options','nosniff');h.set('permissions-policy','camera=(),microphone=(),geolocation=()');h.set('content-security-policy',bespoke?"default-src 'none'; img-src 'self' data:; style-src 'self' https://fonts.googleapis.com; script-src 'self'; font-src 'self' https://fonts.gstatic.com; connect-src 'self'; form-action 'self'; frame-ancestors 'none'; base-uri 'self'":"default-src 'none'; img-src 'self' data:; style-src 'self'; script-src 'self'; font-src 'self'; connect-src 'self'; form-action 'self'; frame-ancestors 'none'; base-uri 'self'");return new Response(r.body,{status:r.status,statusText:r.statusText,headers:h})}
async function jsonBody(req){const len=Number(req.headers.get('content-length')||0);if(len>MAX_JSON)throw Object.assign(Error('Dữ liệu vượt kích thước cho phép'),{isUserError:true});const raw=await req.text();if(raw.length>MAX_JSON)throw Object.assign(Error('Dữ liệu vượt kích thước cho phép'),{isUserError:true});try{return JSON.parse(raw)}catch{throw Object.assign(Error('Dữ liệu JSON không hợp lệ'),{isUserError:true})}}
function roleFor(url,env){const dev=['localhost','127.0.0.1'].includes(url.hostname) && env.PREVIEW_MODE==='true';const preview=url.hostname===(env.PREVIEW_HOST||'jotrip-quote-preview.kenzuko.workers.dev')&&env.PREVIEW_MODE==='true';if(dev||preview)return 'preview';if(url.hostname===(env.PUBLIC_HOST||'jotrip.vn'))return 'public';if(url.hostname===(env.STAFF_HOST||'quote.jotrip.vn'))return 'staff';return 'unknown'}
function originMatches(req){const origin=req.headers.get('origin');return origin === new URL(req.url).origin}
function nameCookie(req){return new URL(req.url).protocol==='https:'?'__Host-jq_staff':'jq_staff_preview'}
function sessionCookie(req,value,maxAge){const sec=new URL(req.url).protocol==='https:'?'; Secure':'';return `${nameCookie(req)}=${value}; Path=/; HttpOnly; SameSite=Strict${sec}; Max-Age=${maxAge}`}
async function currentSession(req,env){const ck=req.headers.get('cookie')||'';const tokenValue=ck.split(';').map(x=>x.trim()).find(x=>x.startsWith(nameCookie(req)+'='))?.split('=')[1];if(!tokenValue||!/^[0-9a-f]{64}$/.test(tokenValue)||!env.DB)return null;const hash=await sha256(tokenValue);const row=await env.DB.prepare('SELECT csrf_token,expires_at FROM staff_sessions WHERE token_hash=?').bind(hash).first();if(!row||Number(row.expires_at)<Date.now())return null;return {hash,csrf:row.csrf_token}}
function constantEq(a,b){if(a.length!==b.length)return false;let val=0;for(let i=0;i<a.length;i++)val|=a[i]^b[i];return val===0}
async function checkPassword(pass,env){if(!env.ADMIN_PASSWORD_HASH||!env.ADMIN_PASSWORD_SALT||!env.ADMIN_EMAIL)return false;const b64=v=>Uint8Array.from(atob(v),c=>c.charCodeAt(0));const salt=b64(env.ADMIN_PASSWORD_SALT),expected=b64(env.ADMIN_PASSWORD_HASH);const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(pass),'PBKDF2',false,['deriveBits']);const actual=new Uint8Array(await crypto.subtle.deriveBits({name:'PBKDF2',salt,iterations:310000,hash:'SHA-256'},key,256));return constantEq(actual,expected)}
async function limit(env,req,action,max,windowMs){if(!env.DB)return false;const ip=req.headers.get('cf-connecting-ip')||'unidentified';const digest=await sha256((env.RATE_LIMIT_SALT||'preview-only')+'|'+ip);const now=Date.now();const row=await env.DB.prepare('SELECT hits,window_start FROM public_rate_limits WHERE ip_hash=? AND action=?').bind(digest,action).first();if(!row||now-Number(row.window_start)>windowMs){await env.DB.prepare('INSERT INTO public_rate_limits(ip_hash,action,window_start,hits) VALUES(?,?,?,1) ON CONFLICT(ip_hash,action) DO UPDATE SET window_start=excluded.window_start,hits=1').bind(digest,action,now).run();return true}if(Number(row.hits)>=max)return false;await env.DB.prepare('UPDATE public_rate_limits SET hits=hits+1 WHERE ip_hash=? AND action=?').bind(digest,action).run();return true}
async function handlePublic(req,env,path){const method=req.method;if(path==='/__demo-home' && env.PREVIEW_MODE==='true' && method==='GET')return html(entry(),200,true);if(path==='/bespoke' && method==='GET')return env.ASSETS.fetch(new Request(new URL('/bespoke/index.html',req.url),{method:'GET'}));if(path==='/quote'&&method==='GET')return html(layout('<main class="wrap simple"><p class="eyebrow">JOTRIP PROPOSALS</p><h1>Hành trình của bạn, từng chi tiết đều có lý do.</h1><p>Khi JoTrip hoàn thành đề xuất, bạn sẽ nhận đường dẫn riêng để xem lịch trình, góp ý và tải Word khi cần.</p><a class="btn yellow" href="/bespoke">Thiết kế chuyến đi →</a></main>',{title:'JoTrip Proposals',indexable:true}),200,true);
 if(path==='/bespoke/api/submit'&&method==='POST'){
  if(env.PRIVACY_NOTICE_APPROVED!=='true')return err('Chức năng gửi yêu cầu chưa mở. Vui lòng liên hệ JoTrip qua hotline hoặc email.',503);
  if(env.PREVIEW_MODE==='true'&&env.ALLOW_PREVIEW_SUBMISSIONS!=='true')return err('Môi trường thử nghiệm chưa nhận dữ liệu khách.',503);
  if(!originMatches(req))return err('Origin không hợp lệ',403);
  if(!(await limit(env,req,'bespoke',5,60*60*1000)))return err('Bạn gửi hơi nhanh. Vui lòng thử lại sau.',429);
  const b=await jsonBody(req);if(b.website)return respond({ok:true,code:'Đã tiếp nhận'});const key=String(b.requestKey||'');if(!/^[a-zA-Z0-9-]{28,100}$/.test(key))return err('Mã yêu cầu chưa hợp lệ');let data;try{data=normalizeRequest(b)}catch(e){return err(e.message)}
  const hash=await sha256(key);const old=await env.DB.prepare('SELECT public_code FROM bespoke_requests WHERE request_key_hash=?').bind(hash).first();if(old)return respond({ok:true,code:old.public_code,duplicate:true});const now=Date.now(),id=crypto.randomUUID(),code='BQ-'+publicCode();
  await env.DB.prepare('INSERT OR IGNORE INTO bespoke_requests(id,request_key_hash,public_code,payload_json,status,source,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)').bind(id,hash,code,JSON.stringify(data),'submitted','bespoke',now,now).run();const recorded=await env.DB.prepare('SELECT public_code FROM bespoke_requests WHERE request_key_hash=?').bind(hash).first();return respond({ok:true,code:recorded.public_code},201);
 }
 const m=path.match(/^\/quote\/p\/([a-f0-9]{64})(?:\/(word|feedback))?\/?$/i);
 if(m){const hash=await sha256(m[1]);const share=await env.DB.prepare('SELECT s.quote_id,s.version_id,v.public_json FROM share_links s JOIN quote_versions v ON v.id=s.version_id WHERE s.token_hash=? AND s.revoked_at IS NULL AND s.expires_at>?').bind(hash,Date.now()).first();if(!share)return html(layout('<main class="wrap simple"><h1>Đường dẫn đã hết hạn hoặc không còn khả dụng.</h1><p>Vui lòng liên hệ JoTrip để nhận bản đề xuất mới.</p></main>'),404);
  const snapshot=JSON.parse(share.public_json);if(!m[2]&&method==='GET')return html(proposal(snapshot,m[1]));if(m[2]==='word'&&method==='GET'){const bytes=makeWord(snapshot);return new Response(bytes,{headers:{'content-type':'application/vnd.openxmlformats-officedocument.wordprocessingml.document','content-disposition':`attachment; filename="JoTrip-Proposal.docx"`,'cache-control':'private,no-store','x-content-type-options':'nosniff'}})}
  if(m[2]==='feedback'&&method==='POST'){if(!originMatches(req))return err('Origin không hợp lệ',403);if(!(await limit(env,req,'feedback',18,60*60*1000)))return err('Quá nhiều góp ý trong thời gian ngắn.',429);const b=await jsonBody(req);const section=String(b.section||'');if(!/^(day-\d{1,2}|option-\d{1,2}|general)$/.test(section))return err('Hạng mục góp ý không hợp lệ');const note=String(b.note||'').trim().slice(0,1600);if(note.length<4)return err('Hãy viết thêm một chút để JoTrip hiểu ý bạn.');await env.DB.prepare("INSERT INTO feedback(id,quote_id,version_id,section_key,guest_name,note,created_at,status) VALUES(?,?,?,?,?,?,?,'new')").bind(crypto.randomUUID(),share.quote_id,share.version_id,section,String(b.guestName||'Khách').trim().slice(0,90),note,Date.now()).run();return respond({ok:true,message:'JoTrip đã nhận được góp ý. Cảm ơn bạn.'},201)}return err('Method not allowed',405)}
 return html('Không tìm thấy trang',404);
}
async function handleStaff(req,env,path){if(path==='/login'&&req.method==='GET')return html(login());const session=await currentSession(req,env);if(path==='/api/staff/login'&&req.method==='POST'){
  if(!originMatches(req))return err('Origin không hợp lệ',403);if(!(await limit(env,req,'login',8,15*60*1000)))return err('Quá nhiều lần thử. Vui lòng đợi trước khi đăng nhập lại.',429);const b=await jsonBody(req);const email=String(b.email||'').trim().toLowerCase();if(email!==String(env.ADMIN_EMAIL||'').trim().toLowerCase()||!(await checkPassword(String(b.password||''),env)))return err('Email hoặc mật khẩu chưa đúng',401);
  const key=token(),csrf=token(16),hash=await sha256(key),now=Date.now();await env.DB.prepare('INSERT INTO staff_sessions(token_hash,csrf_token,expires_at,created_at) VALUES(?,?,?,?)').bind(hash,csrf,now+SESSION_AGE*1000,now).run();return respond({ok:true},200,{'set-cookie':sessionCookie(req,key,SESSION_AGE)});
 }
 if(!session){if(path.startsWith('/api/'))return err('Cần đăng nhập',401);return Response.redirect(new URL('/login',req.url).toString(),302)}
 if(path==='/api/staff/me'&&req.method==='GET')return respond({ok:true,csrf:session.csrf});if(path==='/studio'&&req.method==='GET')return html(staff());if(path==='/'&&req.method==='GET')return Response.redirect(new URL('/studio',req.url).toString(),302);
 if(path.startsWith('/api/staff/')&&req.method!=='GET'){
  if(!originMatches(req)||req.headers.get('x-csrf-token')!==session.csrf)return err('Yêu cầu bảo mật không hợp lệ',403);
 }
 if(path==='/api/staff/logout'&&req.method==='POST'){await env.DB.prepare('DELETE FROM staff_sessions WHERE token_hash=?').bind(session.hash).run();return respond({ok:true},200,{'set-cookie':sessionCookie(req,'',0)})}
 if(path==='/api/staff/requests'&&req.method==='GET'){const q=await env.DB.prepare('SELECT id,public_code,payload_json,status,created_at FROM bespoke_requests ORDER BY created_at DESC LIMIT 100').all();return respond({ok:true,requests:(q.results||[]).map(r=>({...r,payload:JSON.parse(r.payload_json),payload_json:undefined}))})}
 if(path==='/api/staff/quotes'&&req.method==='GET'){const rows=await env.DB.prepare('SELECT id,public_code,title,client_name,status,latest_version,updated_at FROM quotes ORDER BY updated_at DESC LIMIT 100').all();return respond({ok:true,quotes:rows.results||[]})}
 if(path==='/api/staff/quotes'&&req.method==='POST'){const b=await jsonBody(req);let draft;try{draft=normalizeDraft(b.draft)}catch(e){return err(e.message)}const id=crypto.randomUUID(),now=Date.now(),code='JQ-'+publicCode();await env.DB.prepare('INSERT INTO quotes(id,public_code,title,client_name,draft_json,status,latest_version,created_at,updated_at) VALUES(?,?,?,?,?,\'draft\',0,?,?)').bind(id,code,draft.title,draft.clientSalutation,JSON.stringify(draft),now,now).run();await env.DB.prepare('INSERT INTO quote_audit(id,quote_id,action,detail,created_at) VALUES(?,?,?,?,?)').bind(crypto.randomUUID(),id,'create',String(b.requestId||'manual').slice(0,60),now).run();if(b.requestId)await env.DB.prepare("UPDATE bespoke_requests SET status='quoted',updated_at=? WHERE id=?").bind(now,String(b.requestId)).run();return respond({ok:true,id,code},201)}
 const qm=path.match(/^\/api\/staff\/quotes\/([a-f0-9-]{36})(?:\/(publish|revoke|feedback))?$/i);if(qm){const id=qm[1];const quote=await env.DB.prepare('SELECT * FROM quotes WHERE id=?').bind(id).first();if(!quote)return err('Không tìm thấy báo giá',404);
  if(!qm[2]&&req.method==='GET'){const links=await env.DB.prepare('SELECT token_hash,version_id,expires_at,revoked_at,created_at FROM share_links WHERE quote_id=? ORDER BY created_at DESC LIMIT 20').bind(id).all();return respond({ok:true,quote:{...quote,draft:JSON.parse(quote.draft_json),draft_json:undefined},links:links.results||[]})}
  if(!qm[2]&&req.method==='PUT'){const b=await jsonBody(req);let draft;try{draft=normalizeDraft(b)}catch(e){return err(e.message)}await env.DB.prepare("UPDATE quotes SET title=?,client_name=?,draft_json=?,status='draft',updated_at=? WHERE id=?").bind(draft.title,draft.clientSalutation,JSON.stringify(draft),Date.now(),id).run();return respond({ok:true,id})}
  if(qm[2]==='feedback'&&req.method==='GET'){const f=await env.DB.prepare('SELECT version_id,section_key,guest_name,note,created_at,status FROM feedback WHERE quote_id=? ORDER BY created_at DESC LIMIT 100').bind(id).all();return respond({ok:true,feedback:f.results||[]})}
  if(qm[2]==='publish'&&req.method==='POST'){const b=await jsonBody(req);if(b.approvePrice!==true||b.approveMedia!==true)return err('Cần xác nhận giá bán, ảnh và điều khoản trước khi phát hành');let publicData;try{publicData=approvePublic(JSON.parse(quote.draft_json))}catch(e){return err(e.message)}const now=Date.now(),ver=Number(quote.latest_version)+1,vid=crypto.randomUUID(),plain=token();const hash=await sha256(plain),expires=now+Math.min(90,Math.max(1,Number(b.daysValid)||30))*86400000;try{await env.DB.batch([env.DB.prepare("UPDATE quotes SET latest_version=?,status='published',updated_at=? WHERE id=? AND latest_version=?").bind(ver,now,id,quote.latest_version),env.DB.prepare('INSERT INTO quote_versions(id,quote_id,version_no,public_json,created_at) VALUES(?,?,?,?,?)').bind(vid,id,ver,JSON.stringify(publicData),now),env.DB.prepare('INSERT INTO share_links(token_hash,quote_id,version_id,expires_at,created_at) VALUES(?,?,?,?,?)').bind(hash,id,vid,expires,now),env.DB.prepare('INSERT INTO quote_audit(id,quote_id,action,detail,created_at) VALUES(?,?,?,?,?)').bind(crypto.randomUUID(),id,'publish','v'+ver,now)]);}catch(e){return err('Báo giá vừa được cập nhật. Hãy tải lại và thử lại.',409)}const publicHost=env.PUBLIC_HOST||'jotrip.vn';const url=env.PREVIEW_MODE==='true'?new URL('/quote/p/'+plain,req.url).toString():`https://${publicHost}/quote/p/${plain}`;return respond({ok:true,version:ver,url,expiresAt:expires},201)}
  if(qm[2]==='revoke'&&req.method==='POST'){const b=await jsonBody(req);const hash=String(b.tokenHash||'');if(!/^[a-f0-9]{64}$/.test(hash))return err('Mã liên kết không hợp lệ');await env.DB.prepare('UPDATE share_links SET revoked_at=? WHERE quote_id=? AND token_hash=? AND revoked_at IS NULL').bind(Date.now(),id,hash).run();return respond({ok:true})}
 }
 return err('Không tìm thấy thao tác',404);
}
export default {async fetch(req,env){return wrap(req,async()=>{const url=new URL(req.url),role=roleFor(url,env),path=url.pathname;if(role==='unknown')return security(err('Host không hợp lệ',404));if(role==='preview'&&env.PREVIEW_LOCK!=='false')return security(html('<main style="font:18px system-ui;padding:48px;max-width:650px;margin:auto"><h1>JoTrip Bespoke - đang hoàn thiện bản thử nghiệm</h1><p>Trang này chưa nhận thông tin khách. Vui lòng quay lại sau.</p></main>',503));if(role==='preview'&&env.ENABLE_STAFF_PREVIEW!=='true'&&(path==='/'||path==='/login'||path.startsWith('/studio')||path.startsWith('/api/staff/')))return security(err('Quote Studio chưa mở trên môi trường thử nghiệm',403));if(env.ASSETS&&(path.startsWith('/assets/')||path.startsWith('/bespoke/assets/')||path==='/bespoke/app.js'||path==='/bespoke/app.css'))return security(await env.ASSETS.fetch(req),path.startsWith('/bespoke/'));if(!env.DB){if(path==='/api/health')return security(respond({ok:false,dbReady:false},503));return security(html('<h1>Ứng dụng đang được cấu hình</h1>',503))}if(role==='public')return security(await handlePublic(req,env,path),path==='/bespoke');if(role==='staff')return security(await handleStaff(req,env,path));if(role==='preview'){const staffPath=path==='/'||path.startsWith('/studio')||path==='/login'||path.startsWith('/api/staff/');return security(staffPath?await handleStaff(req,env,path):await handlePublic(req,env,path),path==='/bespoke')}return security(err('Not found',404))})}}
